services:
  match-api:
    build:
      context: ./match-api
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - ACCESS_JWT_SIGN_KEY=${ACCESS_JWT_SIGN_KEY}
      - REFRESH_JWT_SIGN_KEY=${REFRESH_JWT_SIGN_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PORT=${DATABASE_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - STRIPE_PRICE_MONTHLY=${STRIPE_PRICE_MONTHLY}
      - STRIPE_PRICE_ANNUAL=${STRIPE_PRICE_ANNUAL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - QR_SECRET=${QR_SECRET}
      - LOCATIONIQ_KEY=${LOCATIONIQ_KEY}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_SEND_MAIL=${SMTP_SEND_MAIL}
      - SMTP_SEND_NAME=${SMTP_SEND_NAME}
    networks:
      - match-network
    depends_on:
        mail-worker:
            condition: service_started

  mail-worker:
    build:
      context: ./match-api/services/mail-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SEND_MAIL=${SMTP_SEND_MAIL}

  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - match-network

  match:
    build:
      context: ./match-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      match-api:
        condition: service_started
    networks:
      - match-network

    
networks:
  match-network:
    driver: bridge

volumes:
  redis_data:
