services:
  match-api:
    build:
      context: ./match-api
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - ACCESS_JWT_SIGN_KEY=${ACCESS_JWT_SIGN_KEY}
      - REFRESH_JWT_SIGN_KEY=${REFRESH_JWT_SIGN_KEY}
    networks:
      - match-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.match-api.rule=Host(`api.match.dokploy.app`)"
      - "traefik.http.services.match-api.loadbalancer.server.port=8008"

  match:
    build:
      context: ./match-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://match-api:8008
    depends_on:
      match-api:
        condition: service_started
    networks:
      - match-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.match-frontend.rule=Host(`match.dokploy.app`)"
      - "traefik.http.services.match-frontend.loadbalancer.server.port=3001"

networks:
  match-network:
    driver: bridge
